menu:
  Home: /  
  Archives: /archives
  Categories: /categories
  About: /about
  Tags: /tags
  #GitHub: https://github.com/KevinWu1993
  Links: /link
  RSS: /atom.xml

# duoshuo comment
duoshuo: true
duoshuo_name: kevinwu1993

# google analytics
# googleTrackId: 

